version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bawa@2004
      MYSQL_DATABASE: cr_db
      MYSQL_USER: root
      MYSQL_PASSWORD: bawa@2004
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  react-app:
    build: ./react-app
    ports:
      - "5173:5173"
    depends_on:
      - db

volumes:
  db_data:
